// <auto-generated />
namespace LastraJulian_LPPA_Parcial1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mgAfiliados : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mgAfiliados));
        
        string IMigrationMetadata.Id
        {
            get { return "202105312316100_mgAfiliados"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
